
version: 2.1
orbs:
    node: circleci/node@5.0.3
jobs:
    build-and-deploy:
        docker:
            - image: cimg/node:19.0.1
        steps:
            - checkout
            - run:
                  command: sudo npm i -g serverless npm@latest
            - run:
                  command: npm install
            - run:
                  command: ./.circleci/install-credentials.sh
            - run:
                  command: sls deploy

workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  context: serverlessProject
                  filters:
                      branches:
                          only:
                              - master