name: serverless-ci-deployment

on: 
  push:
    branches:
      - master
  
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Install serverless globally
        run: npm install -g serverless
      
      - name: Configure serverless authentication
        run: 	serverless config credentials \
         --provider aws \
         --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
         --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
         --profile serverlessUser
      
      - name: Install npm dependencies
        run: npm ci
     
      - name: Deploy lambda function
        run: sls deploy